#!/usr/bin/env bash
# ============================================================================
# apply-admin-ips.sh — применение admin-ips.inc из env ADMIN_PUBLIC_IPS
# ----------------------------------------------------------------------------
# Usage:
#   sudo ADMIN_PUBLIC_IPS='203.0.113.42/32,198.51.100.7/32' ./apply-admin-ips.sh
#
# Что делает:
#   1. Парсит CSV из ADMIN_PUBLIC_IPS.
#   2. Валидирует формат каждой записи (IPv4/CIDR).
#   3. Пишет /etc/nginx/conf.d/admin-ips.inc.new.
#   4. nginx -t → если OK, mv .new → .inc + nginx -s reload.
#   5. Если nginx -t FAIL → rm .new + откат (оригинал не тронут).
#
# Примечание: скрипт НЕ читает и не сохраняет историю — каждый запуск
# ПОЛНОСТЬЮ перезаписывает admin-ips.inc. Чтобы добавить IP к существующим,
# передай полный список.
# ============================================================================
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: скрипт должен запускаться от root (sudo)." >&2
    exit 1
fi

if [[ -z "${ADMIN_PUBLIC_IPS:-}" ]]; then
    echo "ERROR: env ADMIN_PUBLIC_IPS не задан." >&2
    echo "Usage: sudo ADMIN_PUBLIC_IPS='1.2.3.4/32,5.6.7.8/32' $0" >&2
    exit 2
fi

for cmd in nginx; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: не найден бинарь '$cmd'." >&2
        exit 3
    fi
done

TARGET="/etc/nginx/conf.d/admin-ips.inc"
STAGE="${TARGET}.new"
BACKUP="${TARGET}.bak-$(date +%Y%m%d-%H%M%S)"

# ---- Парсинг CSV + валидация -----------------------------------------------
# IPv4 CIDR regex: 0-255 по октетам + /0-32.
IP_RE='^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}/(3[0-2]|[12]?[0-9])$'

{
    echo "# ========================================================="
    echo "# admin-ips.inc — auto-generated by apply-admin-ips.sh"
    echo "# Дата: $(date -Iseconds)"
    echo "# Источник: env ADMIN_PUBLIC_IPS"
    echo "# ========================================================="
} > "$STAGE"

IFS=',' read -ra IPS <<< "$ADMIN_PUBLIC_IPS"
COUNT=0
for raw in "${IPS[@]}"; do
    # trim пробелов
    ip="${raw// /}"
    [[ -z "$ip" ]] && continue

    if [[ ! "$ip" =~ $IP_RE ]]; then
        echo "ERROR: некорректный CIDR: '$ip'. Ожидается формат 'x.x.x.x/yy'." >&2
        rm -f "$STAGE"
        exit 4
    fi

    echo "${ip} 1;  # applied $(date +%Y-%m-%d)" >> "$STAGE"
    COUNT=$((COUNT + 1))
done

if [[ "$COUNT" -eq 0 ]]; then
    echo "ERROR: ни один IP не распознан в ADMIN_PUBLIC_IPS." >&2
    rm -f "$STAGE"
    exit 5
fi

# ---- Backup существующего (если есть) --------------------------------------
if [[ -f "$TARGET" ]]; then
    cp -a "$TARGET" "$BACKUP"
    echo "Backup: $BACKUP"
fi

# ---- Атомарный mv + проверка nginx ----------------------------------------
mv "$STAGE" "$TARGET"

if ! nginx -t 2>&1; then
    echo "ERROR: nginx -t FAILED. Откатываю на предыдущую версию." >&2
    if [[ -f "$BACKUP" ]]; then
        mv "$BACKUP" "$TARGET"
        echo "Откат выполнен: $TARGET ← $BACKUP" >&2
    else
        # если backup'а не было — просто удаляем невалидный файл
        rm -f "$TARGET"
        echo "Невалидный $TARGET удалён (оригинала не было)." >&2
    fi
    exit 6
fi

# ---- Reload ----------------------------------------------------------------
if ! nginx -s reload; then
    echo "ERROR: nginx -s reload провалился." >&2
    exit 7
fi

echo "OK: применено ${COUNT} IP в $TARGET, nginx reloaded."
echo "Проверка: curl -sI https://svoefoto.ru/employee/ -H 'Host: svoefoto.ru'"
