BEGIN;

-- Extended print options (currently hardcoded in publisher.rs)
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS nup INTEGER DEFAULT 1;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS "collate" BOOLEAN DEFAULT TRUE;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS resolution_dpi INTEGER DEFAULT 0;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS color_auto_detect BOOLEAN DEFAULT FALSE;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS booklet BOOLEAN DEFAULT FALSE;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS pages_per_sheet INTEGER DEFAULT 0;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS binding VARCHAR(20) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS staple_position VARCHAR(30) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS hole_punch VARCHAR(20) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS hole_punch_type VARCHAR(20) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS duplex_mode VARCHAR(20) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS scaling_percent INTEGER DEFAULT 0;
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS output_bin VARCHAR(30) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS toner_save VARCHAR(10) DEFAULT 'off';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS department_id VARCHAR(30) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS secure_pin VARCHAR(10) DEFAULT '';
ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS gray_mode VARCHAR(20) DEFAULT '';

COMMIT;
