use axum::{
    Json,
    extract::{Path, State},
};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{AppState, error::AppError};

/// Send a command to a monitor agent via MQTT.
/// POST /api/infra/agents/:id/monitor/:command
///
/// Supported commands: exec, sysinfo, service, logs, file
#[derive(Deserialize)]
pub struct MonitorCommandRequest {
    /// Unique request ID for correlation (generated by client)
    pub request_id: String,
    /// Command-specific payload (JSON, forwarded to agent as-is)
    pub payload: serde_json::Value,
}

#[derive(Serialize)]
pub struct MonitorCommandResponse {
    pub request_id: String,
    pub status: String,
    pub message: String,
}

pub async fn send_command(
    State(state): State<AppState>,
    Path((agent_id, command)): Path<(Uuid, String)>,
    Json(req): Json<MonitorCommandRequest>,
) -> Result<Json<MonitorCommandResponse>, AppError> {
    // Validate command
    let allowed = ["exec", "sysinfo", "service", "logs", "file"];
    if !allowed.contains(&command.as_str()) {
        return Err(AppError::bad_request(format!(
            "Unknown monitor command: {command}. Allowed: {allowed:?}"
        )));
    }

    // Look up agent to get studio_id
    let agent = sqlx::query_as::<_, AgentRow>(
        "SELECT id, studio_id, agent_type FROM agents WHERE id = $1 AND is_active = true",
    )
    .bind(agent_id)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::not_found("Agent not found"))?;

    if agent.agent_type != "monitor" {
        return Err(AppError::bad_request(format!(
            "Agent {} is type '{}', not 'monitor'",
            agent_id, agent.agent_type
        )));
    }

    // Build MQTT topic: svoefoto/{studio_id}/monitor/commands/{command}
    let topic = format!("svoefoto/{}/monitor/commands/{}", agent.studio_id, command);

    // Build JSON payload with request_id
    let mut payload = req.payload.clone();
    if let Some(obj) = payload.as_object_mut() {
        obj.insert("request_id".to_string(), serde_json::json!(req.request_id));
    }

    let payload_bytes = serde_json::to_vec(&payload)?;

    // Publish via MQTT
    let guard = state.mqtt_client.read().await;
    let client = guard
        .as_ref()
        .ok_or_else(|| AppError::Internal("MQTT bridge not connected".into()))?;

    client
        .publish(&topic, rumqttc::QoS::AtLeastOnce, false, payload_bytes)
        .await
        .map_err(|e| AppError::Internal(format!("MQTT publish failed: {e}")))?;

    tracing::info!(
        agent_id = %agent_id,
        command = %command,
        request_id = %req.request_id,
        "Monitor command sent via MQTT"
    );

    Ok(Json(MonitorCommandResponse {
        request_id: req.request_id,
        status: "sent".into(),
        message: format!("Command '{command}' dispatched to agent {agent_id}"),
    }))
}

#[allow(dead_code)]
#[derive(sqlx::FromRow)]
struct AgentRow {
    id: Uuid,
    studio_id: Uuid,
    agent_type: String,
}
