import { errorResponse } from './types.js';

export const SELECTEL_CONFIRM = {
  DNS_CREATE_RECORD: 'CREATE_SELECTEL_DNS_RECORD',
  DNS_UPDATE_RECORD: 'UPDATE_SELECTEL_DNS_RECORD',
  DNS_DELETE_RECORD: 'DELETE_SELECTEL_DNS_RECORD',
  DNS_CREATE_ZONE: 'CREATE_SELECTEL_DNS_ZONE',
  DNS_DELETE_ZONE: 'DELETE_SELECTEL_DNS_ZONE',
  CERT_UPLOAD: 'UPLOAD_SELECTEL_CERT',
  CERT_DELETE: 'DELETE_SELECTEL_CERT',
  LETSENCRYPT_ISSUE: 'ISSUE_SELECTEL_LETSENCRYPT_CERT',
  TICKET_CREATE: 'CREATE_SELECTEL_TICKET',
  TICKET_COMMENT: 'COMMENT_SELECTEL_TICKET',
  TICKET_CLOSE: 'CLOSE_SELECTEL_TICKET',
  SERVER_REBOOT: 'REBOOT_SELECTEL_SERVER',
  NETWORK_UPDATE_PTR: 'UPDATE_SELECTEL_PTR',
  FARM_CREATE_GROUP: 'CREATE_SELECTEL_FARM_GROUP',
  FARM_DELETE_GROUP: 'DELETE_SELECTEL_FARM_GROUP',
  FARM_ADD_DEVICE_TO_GROUP: 'ADD_SELECTEL_FARM_DEVICE',
  FARM_REMOVE_DEVICE: 'REMOVE_SELECTEL_FARM_DEVICE',
  FARM_ASSIGN_DEVICE: 'ASSIGN_SELECTEL_FARM_DEVICE',
  FARM_RELEASE_DEVICE: 'RELEASE_SELECTEL_FARM_DEVICE',
  FARM_ADB_CONNECT: 'CONNECT_SELECTEL_FARM_ADB',
  FARM_ADB_DISCONNECT: 'DISCONNECT_SELECTEL_FARM_ADB',
  FARM_ADD_ADB_KEY: 'ADD_SELECTEL_FARM_ADB_KEY',
} as const;

export function requireConfirm(confirm: string | undefined, expected: string, action: string) {
  if (confirm === expected) {
    return null;
  }

  return errorResponse(`Refusing to ${action}. Pass confirm="${expected}".`);
}
