/**
 * Machine-readable error codes for API responses.
 * Frontend can match on `response.code` instead of parsing human-readable messages.
 *
 * Convention: UPPER_SNAKE_CASE, grouped by domain.
 */
export const ErrorCode = {
  // ── Generic ──────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_IP: 'FORBIDDEN_IP',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CAPTCHA_REQUIRED: 'CAPTCHA_REQUIRED',
  CAPTCHA_INVALID: 'CAPTCHA_INVALID',
  CAPTCHA_UNAVAILABLE: 'CAPTCHA_UNAVAILABLE',

  // ── Auth ─────────────────────────────────────────────
  AUTH_CODE_MISSING: 'AUTH_CODE_MISSING',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_LOCKOUT: 'AUTH_LOCKOUT',
  AUTH_RESET_LINK_EXPIRED: 'AUTH_RESET_LINK_EXPIRED',

  // ── 2FA / Phone verification ─────────────────────────
  PHONE_INVALID: 'PHONE_INVALID',
  PHONE_CODE_EXPIRED: 'PHONE_CODE_EXPIRED',
  PHONE_CODE_INVALID: 'PHONE_CODE_INVALID',
  PHONE_CODE_MAX_ATTEMPTS: 'PHONE_CODE_MAX_ATTEMPTS',
  PHONE_SEND_LIMIT: 'PHONE_SEND_LIMIT',
  PHONE_SEND_FAILED: 'PHONE_SEND_FAILED',
  PHONE_SEND_BUSY: 'PHONE_SEND_BUSY',
  PHONE_VERIFY_LIMIT: 'PHONE_VERIFY_LIMIT',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',

  // ── Gift activation (account-first) ──────────────────
  GIFT_PROMO_INVALID: 'GIFT_PROMO_INVALID',
  ACTIVATION_SESSION_INVALID: 'ACTIVATION_SESSION_INVALID',
  ACTIVATION_CODE_LOCKED: 'ACTIVATION_CODE_LOCKED',
  ACTIVATION_NOT_VERIFIED: 'ACTIVATION_NOT_VERIFIED',
  ACTIVATION_RATE_LIMITED: 'ACTIVATION_RATE_LIMITED',
  ACTIVATION_DISABLED: 'ACTIVATION_DISABLED',
  EMAIL_CODE_INVALID: 'EMAIL_CODE_INVALID',
  EMAIL_CODE_EXPIRED: 'EMAIL_CODE_EXPIRED',

  // ── Payments ─────────────────────────────────────────
  PAYMENT_AMOUNT_REQUIRED: 'PAYMENT_AMOUNT_REQUIRED',
  PAYMENT_SYSTEM_NOT_CONFIGURED: 'PAYMENT_SYSTEM_NOT_CONFIGURED',
  PAYMENT_SBP_FAILED: 'PAYMENT_SBP_FAILED',
  PAYMENT_QR_FAILED: 'PAYMENT_QR_FAILED',
  PAYMENT_ORDER_NOT_FOUND: 'PAYMENT_ORDER_NOT_FOUND',
  PAYMENT_ORDER_INVALID_STATUS: 'PAYMENT_ORDER_INVALID_STATUS',
  PAYMENT_LINK_NOT_FOUND: 'PAYMENT_LINK_NOT_FOUND',
  PAYMENT_LINK_NOT_PAID: 'PAYMENT_LINK_NOT_PAID',
  PAYMENT_LINK_EXPIRED: 'PAYMENT_LINK_EXPIRED',
  PAYMENT_LINKS_DISABLED: 'PAYMENT_LINKS_DISABLED',
  WORKDAY_NOT_STARTED: 'WORKDAY_NOT_STARTED',

  // ── POS ──────────────────────────────────────────────
  POS_SHIFT_ALREADY_OPEN: 'POS_SHIFT_ALREADY_OPEN',
  POS_SHIFT_NOT_FOUND: 'POS_SHIFT_NOT_FOUND',
  POS_RECEIPT_NOT_FOUND: 'POS_RECEIPT_NOT_FOUND',
  POS_RECEIPT_ALREADY_VOIDED: 'POS_RECEIPT_ALREADY_VOIDED',
  POS_RECEIPT_ALREADY_REFUNDED: 'POS_RECEIPT_ALREADY_REFUNDED',
  POS_CANNOT_REFUND_REFUND: 'POS_CANNOT_REFUND_REFUND',
  POS_RECEIPT_WRONG_SHIFT: 'POS_RECEIPT_WRONG_SHIFT',
  POS_SHIFT_CLOSED: 'POS_SHIFT_CLOSED',
  POS_PAYMENTS_MISMATCH: 'POS_PAYMENTS_MISMATCH',
  POS_RECEIPT_ITEMS_MISMATCH: 'POS_RECEIPT_ITEMS_MISMATCH',
  POS_REFUND_QTY_EXCEEDED: 'POS_REFUND_QTY_EXCEEDED',
  POS_BRIDGE_UNAVAILABLE: 'POS_BRIDGE_UNAVAILABLE',
  POS_TERMINAL_OFFLINE: 'POS_TERMINAL_OFFLINE',
  POS_FISCAL_UNAVAILABLE: 'POS_FISCAL_UNAVAILABLE',
  POS_FISCAL_WRONG_STATUS: 'POS_FISCAL_WRONG_STATUS',
  POS_SUBSCRIPTION_REQUIRED: 'POS_SUBSCRIPTION_REQUIRED',
  POS_SUBSCRIPTION_NOT_ACTIVE: 'POS_SUBSCRIPTION_NOT_ACTIVE',
  POS_SUBSCRIPTION_INSUFFICIENT_CREDITS: 'POS_SUBSCRIPTION_INSUFFICIENT_CREDITS',
  POS_SUBSCRIPTION_COVERAGE_MISMATCH: 'POS_SUBSCRIPTION_COVERAGE_MISMATCH',
  POS_SUBSCRIPTION_REFUND_UNSUPPORTED: 'POS_SUBSCRIPTION_REFUND_UNSUPPORTED',

  // ── Orders ───────────────────────────────────────────
  DUPLICATE_ORDER: 'DUPLICATE_ORDER',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  // ── Loyalty ──────────────────────────────────────────
  LOYALTY_INSUFFICIENT_POINTS: 'LOYALTY_INSUFFICIENT_POINTS',

  // ── Education print estimate ─────────────────────────
  PRINT_ANALYZE_UNAVAILABLE: 'PRINT_ANALYZE_UNAVAILABLE',
  PRINT_ESTIMATE_FILE_NOT_FOUND: 'PRINT_ESTIMATE_FILE_NOT_FOUND',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
